// Code generated by MockGen. DO NOT EDIT.
// Source: internal/collector/exec.go
//
// Generated by this command:
//
//	mockgen -source=internal/collector/exec.go -package=collector -destination=internal/collector/mocks_exec_test.go
//

// Package collector is a generated GoMock package.
package collector

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockcmdRunner is a mock of cmdRunner interface.
type MockcmdRunner struct {
	ctrl     *gomock.Controller
	recorder *MockcmdRunnerMockRecorder
	isgomock struct{}
}

// MockcmdRunnerMockRecorder is the mock recorder for MockcmdRunner.
type MockcmdRunnerMockRecorder struct {
	mock *MockcmdRunner
}

// NewMockcmdRunner creates a new mock instance.
func NewMockcmdRunner(ctrl *gomock.Controller) *MockcmdRunner {
	mock := &MockcmdRunner{ctrl: ctrl}
	mock.recorder = &MockcmdRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcmdRunner) EXPECT() *MockcmdRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockcmdRunner) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockcmdRunnerMockRecorder) Run(ctx, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockcmdRunner)(nil).Run), varargs...)
}
