// Code generated by MockGen. DO NOT EDIT.
// Source: internal/collector/os.go
//
// Generated by this command:
//
//	mockgen -source=internal/collector/os.go -package=collector -destination=internal/collector/mocks_os_test.go
//

// Package collector is a generated GoMock package.
package collector

import (
	io "io"
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockosOperator is a mock of osOperator interface.
type MockosOperator struct {
	ctrl     *gomock.Controller
	recorder *MockosOperatorMockRecorder
	isgomock struct{}
}

// MockosOperatorMockRecorder is the mock recorder for MockosOperator.
type MockosOperatorMockRecorder struct {
	mock *MockosOperator
}

// NewMockosOperator creates a new mock instance.
func NewMockosOperator(ctrl *gomock.Controller) *MockosOperator {
	mock := &MockosOperator{ctrl: ctrl}
	mock.recorder = &MockosOperatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockosOperator) EXPECT() *MockosOperatorMockRecorder {
	return m.recorder
}

// CreateTemp mocks base method.
func (m *MockosOperator) CreateTemp(dir, pattern string) (tempFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemp", dir, pattern)
	ret0, _ := ret[0].(tempFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemp indicates an expected call of CreateTemp.
func (mr *MockosOperatorMockRecorder) CreateTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemp", reflect.TypeOf((*MockosOperator)(nil).CreateTemp), dir, pattern)
}

// Open mocks base method.
func (m *MockosOperator) Open(name string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockosOperatorMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockosOperator)(nil).Open), name)
}

// Remove mocks base method.
func (m *MockosOperator) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockosOperatorMockRecorder) Remove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockosOperator)(nil).Remove), name)
}

// Rename mocks base method.
func (m *MockosOperator) Rename(oldpath, newpath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", oldpath, newpath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockosOperatorMockRecorder) Rename(oldpath, newpath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockosOperator)(nil).Rename), oldpath, newpath)
}

// MocktempFile is a mock of tempFile interface.
type MocktempFile struct {
	ctrl     *gomock.Controller
	recorder *MocktempFileMockRecorder
	isgomock struct{}
}

// MocktempFileMockRecorder is the mock recorder for MocktempFile.
type MocktempFileMockRecorder struct {
	mock *MocktempFile
}

// NewMocktempFile creates a new mock instance.
func NewMocktempFile(ctrl *gomock.Controller) *MocktempFile {
	mock := &MocktempFile{ctrl: ctrl}
	mock.recorder = &MocktempFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktempFile) EXPECT() *MocktempFileMockRecorder {
	return m.recorder
}

// Chmod mocks base method.
func (m *MocktempFile) Chmod(mode os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chmod", mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chmod indicates an expected call of Chmod.
func (mr *MocktempFileMockRecorder) Chmod(mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chmod", reflect.TypeOf((*MocktempFile)(nil).Chmod), mode)
}

// Close mocks base method.
func (m *MocktempFile) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MocktempFileMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MocktempFile)(nil).Close))
}

// Name mocks base method.
func (m *MocktempFile) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MocktempFileMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MocktempFile)(nil).Name))
}

// Write mocks base method.
func (m *MocktempFile) Write(b []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", b)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MocktempFileMockRecorder) Write(b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MocktempFile)(nil).Write), b)
}
