receivers:
  journald:
    units: []
    priority: info
    start_at: end

exporters:
  debug:
    verbosity: basic

service:
  pipelines:
    logs:
      receivers: [filelog/kern]
      exporters: [debug]
